INSERT INTO book (idBook, title, description, stock, price) VALUES
    ('1', 'Free Software, Free Society', 'The Free Software movement, of which Open-Source is an offshoot, is, at its core, a philosophy.\n\nThis book explains and applies that philosophy with depth, clarity, and stunning originality.\n\nTopics like software patents and restrictive copyright are also covered from a socio-philosophical perspective.\n\nForget all the other Free Software books - this is straight from the horses mouth, very well written, and full of very exciting ideas and insight.\n\nYou do not need to be technically proficient (ie have any experience with programming) to read and understand these essays. ', '25', '29.89'),

    ('2', 'Free as in Freedom', 'Free as in Freedom interweaves biographical snapshots of GNU project founder Richard Stallman with the political, social and economic history of the free software movement. It examines Stallman\'s unique personality and how that personality has been at turns a driving force and a drawback in terms of the movement\'s overall success.', '32', '19.29'),

    ('3', 'You don\'t Know Javascript', 'It seems like there\'s never been as much widespread desire before for a better way to deeply learn the fundamentals of JavaScript. But with a million blogs, books, and videos out there, just where do you START? Look no further!The worldwide best selling \"You Don\'t Know JS\" book series is back for a 2nd edition: \"You Don\'t Know JS Yet\". All 6 books are brand new, rewritten to cover all sides of JS for 2020 and beyond.\"Get Started\" prepares you for the journey ahead, first surveying the language then detailing how the rest of the You Don\'t Know JS Yet book series guides you to knowing JS more deeply.', '28', '94.99'),
    
    ('4', 'Building React Apps with Server-Side Rendering', 'Leverage the benefits of both client-side and server-side rendering to get the most out of your React applications. By the end of this book you will be able to build and deploy React applications using the Next.js framework to fully render server-side HTML on every Web page.\n\nYou\'ll begin by reviewing JavaScript fundamentals and how they work with the core principles of React. You\'ll then move on to Next.js, the React framework for server-rendered applications. Using this framework, you will create a fast and secure solutional React application that renders content on the server-side, protects sensitive information, and optimizes response times. Before deploying the application using Docker containers, you\'ll create automated unit tests to verify that every component is appropriately doing its job\nBuilding React Apps with Server-Side Rendering also covers other fun and interesting topics such as Bootstrap 4, JSX (JavaScript XML), adding styling to your React applications, and much more. By the end of this book, you will be able to build and deploy React applications that fully render server-side HTML on every page. In the end you\'ll have a client-side rendered React application that integrates server-side rendering into it using Next.js framework.\n\nYou will:\n\n    Examine fundamental concepts of JavaScript (ES 2015)\n    Create client-side apps using JavaScript frameworks React and Redux\n    Add server-side rendering to React apps using the NextJS Framework', '12', '20.40'),
    
    ('5', 'Introducing the HTML5 Web Speech API', 'Leverage the power of HTML5 Web Speech API to quickly add voice capabilities to your websites. This project-oriented book simplifies the process of setting up and manipulating the API in the browser using little more than a text editor or free software. \n\nYou\'ll be presented with a starting toolset that you can use to develop future projects, incorporate into your existing workflow and allow you to take your websites to the next level, reducing the reliance on entering choices through a keyboard and making the overall experience easier for customers.\n\nThis excellent resource is perfect for getting acquainted with creating and manipulating browser-based  APIs. You don’t have to convert your whole work process immediately; you can incorporate as little or as much as you want of the API, and build on this as your skills develop. We live in an age where speed and simplicity are of the essence – this book provides a perfect way to add speech capabilities to our websites, directly in the browser and with the minimum of fuss.\n\nIntroducing the HTML5 Web Speech API is the right choice for developers who want to focus on simplicity to produce properly optimized content in modern browsers using tools already in their possession.\n\nYou will:\n\n    Implement the Web Speech API in a project\n    Explore some of the options for personalizing them for a project\n    Gain an appreciation of pointers around user experience and how this affects the API\n    Understand how to manage issues and security when using the API\n    Work through some example projects, from standalone demos to implementing with other tools or libraries', '15', '24.30'),

    ('6', 'Beggining Git and GitHub', 'Learn the fundamentals of version control through step-by-step tutorials that will teach you the ins-and-outs of Git. This book is your complete guide to how Git and GitHub work in a professional team environment. \n\nDivided into three parts – Version Control, Project Management and Teamwork – this book reveals what waits for you in the real world and how to resolve the problems you may run into. Once past the basics of Git, you\'ll see how to manage a software project, and finally how to utilize Git and GithHub to work effectively as a team.\n\nYou\'ll examine how to plan, follow and execute a project with GitHub, and then apply those concepts to real-world situations. Workaround the pitfalls that most programmers fall into when driving a project with Git by using proven tactics to avoid them. You will also be taught the easiest and quickest ways to resolve merge conflicts. \n\nA lot of modern books on Git don’t go into depth about non-technical topics. Beginning Git and GitHub will help you cover all the bases right at the start of your career.\n\nWhat You\'ll Learn\n\n    Review basic and advanced concepts of Git\n    Apply Project Management skills using GitHub \n    Solve conflicts or, ideally, avoid them altogether\n    Use advanced concepts for a more boosted workflow\n\nWho This book Is For\n\nNew developers, developers that have never worked in a team environment before, developers with basic knowledge of Git or GitHub, or anyone who works with text documents. ', '17', '26.69'),

    ('7', 'Building Progressive Web Applications with Vue.js', 'Obtain all the necessary tools for developing a progressive web application (PWA) with Vue.js, a modern JavaScript framework. You’ll see how PWAs behave like a regular responsive website and have a similar structure to that of a web application, but feel like a native mobile app. Along the way you’ll take advantage of Vue.js features to build fast, high-performing progressive web apps that work offline. \n\nBuilding Progressive Web Applications with Vue.js starts by explaining the basic concepts and structure of PWAs, and moves on to designing the app shell and other features that distinguish a PWA from simple web pages. In the following chapters, the book talks about the improved web technologies, such as service workers, caching strategies, background sync, and push notifications, that make PWAs powerful.\n\nYou will:\n\n    Harness the power of Vue.js to build PWAs \n    Understand the function and relevance of a manifest file\n    Discover service workers and why they are revolutionary\n    Work with the Cache API and caching strategies\n    Use IndexedDB, background sync, and push notifications\n    Enhance your apps with Firebase\n    Implement the Workbox library in your apps', '4', '19.89');
 
