INSERT INTO Video (idVideo, title, description, url, idUser) VALUES
    ('rjL-M9mqPKQ', 'Instalar XAMPP en GNU/Linux (Ubuntu)', 'Explicamos cómo instalar XAMPP en GNU/Linux (Ubuntu 16.04 LTS) para hacer pruebas locales con WordPress, Joomla, Prestashop, y CMS en general.', 'https://www.youtube.com/watch?v=rjL-M9mqPKQ', '1'),
    
    ('sGw4dWpPFTU', 'ES\nComo Instalar MySQL Workbench y Configurarlo con Xampp PhpMyAdmin en Windows | Paso a Paso', 'Hola que tal chicos, hoy les traigo un vídeo que trata sobre como Instalar MySQL Workbench en Windows y configurarlo con Xampp PhpMyAdmin.', 'https://www.youtube.com/watch?v=sGw4dWpPFTU', '1'),
    
    ('e8gaffa3Ca8', 'Curso MySQL - Curso Intensivo y Práctico', 'CONTENIDO:\n\n00:00:28 Qué es MySQL\n00:03:09 Terminología\n00:04:11 Modelo Relacional\n00:06:18 Tipos de dato\n00:09:24 Software para Bases de datos\n00:11:52 Conectar al Servidor SQL por terminal o Shell\n00:12:29 SHOW DATABASES\n00:12:59 CREATE DATABASE\n00:13:54 USE DATABASE\n00:14:36 SHOW TABLES\n00:14:21 CREATE TABLE\n00:19:38 DESCRIBE TABLE\n00:20:50 CRUD\n00:21:18 INSERT\n00:24:16 SELECT\n00:26:26 WHERE\n00:28:02 LIMIT\n00:28:32 UPDATE\n00:31:39 DELETE\n00:34:33 ALTER TABLE ADD\n00:35:47 ALTER TABLE DROP COLUMN\n00:36:46 MySQL  Workbench\n00:37:25 Conectar a Servidor MySQL\n00:38:51 Importar Base de Datos existente\n00:42:38 Table Inspector en Workbench\n00:45:08 ORDER BY\n00:47:21 GROUP BY y COUNT\n00:51:10 INNER JOIN\n00:53:41 INNER JOIN, COUNT y GROUP BY\n00:56:01 DISTINCT\n00:57:46 BETWEEN\n00:58:58 LIKE\n01:01:55 LIKE en 2 Columnas y CONCAT\n01:05:16 IN', 'https://www.youtube.com/watch?v=e8gaffa3Ca8', '2'),

    ('w-0IWyAeZ3M', 'MySQL Workbench Design Walkthrough', 'A walk through on how to design databases in MySQL Workbench.', 'https://www.youtube.com/watch?v=w-0IWyAeZ3M', '2'),
    
    ('c4P__KoPZwo', 'CURSO DE SQL EN MySQL - COMPLETO', 'En este curso veremos el siguiente contenido:\n\nINTRODUCCIÓN  -  00:10\n  - Que es SQL\n  - Que son Gestores de Base de Datos \n  - Pasos para creación de una DB\n  - Tipo de tablas\n  - Partes de una tabla\n  - Tipo de Datos\n  - Instalación de Xampp\n\nDDL - LENGUAJE DE DEFINICIÓN DE DATOS\n  1. CREATE  -  24:11\n   - CREAR USUARIO  \n   - CREATE DATABASE\n   - CREATE TABLE (relacionar tablas)(tabla de enlace)\n  2. DROP  -  43:45\n   - DROP DATABASE  \n   - DROP TABLE (consistencia-integridad)   \n  3. ALTER  -  48:42\n   - ALTER TABLE - RENAME\n   - ALTER TABLE - CHANGE\n   - ALTER TABLE - ADD COLUMN\n   - ALTER TABLE - DROP \n\nDML - LENGUAJE DE MANIPULACIÓN DE DATOS\n  4. INSERT  -  55:16   \n   - IMPORTAR ARCHIVO CSV\n   - EXPORTAR ARCHIVO CSV\n  5. UPDATE  -  1:15:50\n  6. DELETE  -  1:21:32\n  7. SELECT  -  1:29:22\n       - SELECCIONAR REGISTROS  -  1:29:36\n          WHERE\n          IGUAL\n          AND\n          OR\n          MAYOR QUE\n          MAYOR O IGUAL QUE\n          MENOR QUE\n          MENOR O IGUAL QUE\n          DIFERENTE   \n          BETWEEN AND\n          LIKE\n          IN   \n      - FUNCIONES DE ORDENAMIENTO  -  1:48:21   \n          ORDER BY\n          ASC\n          DESC\n      - FUNCIONES DE AGREGACIÓN  -  1:50:47  \n         COUNT\n         SUM\n         MAX\n         MIN\n         AVG\n     - FUNCIONES DE AGRUPAMIENTO  -  1:56:58   \n        GROUP BY\n     - UNIONES  -  1:58:24\n        INNER JOIN\n        LEFT JOIN\n        RIGHT JOIN', 'https://www.youtube.com/watch?v=c4P__KoPZwo', '1'),
    
    ('EHIF9UzdsAM', 'Modelo Entidad Relacion con MySQL Workbench', 'En este tutorial explicaremos como crear un modelo entidad relación utilizando MySQL Workbench. ', 'https://www.youtube.com/watch?v=EHIF9UzdsAM', '1');
 
